import { registration } from "./http/employeeAPI"
import { createAttendance, createClass, createEvent, createParticipant, createStudent } from "./http/modelAPI"

export const seeding = async () => {
        await registration("Владимир", "Иванов", "Учитель", "test1@gmail.com", "1234")      
        await registration("Анна", "Петрова", "Учитель", "test2@gmail.com", "1234")         
        await registration("Мария", "Смирнова", "Учитель", "test3@gmail.com", "1234")       
        await registration("Дмитрий", "Кузнецов", "Учитель", "test4@gmail.com", "1234")     
        await registration("Ольга", "Васильева", "Учитель", "test5@gmail.com", "1234")      
        await registration("Алексей", "Сидоров", "Учитель", "test6@gmail.com", "1234")      
        await registration("Елена", "Фролова", "Учитель", "test7@gmail.com", "1234")        
        await registration("Николай", "Орлов", "Учитель", "test8@gmail.com", "1234")        
        await registration("Татьяна", "Романова", "Учитель", "test9@gmail.com", "1234")     
        await registration("Андрей", "Никитин", "Учитель", "test10@gmail.com", "1234")      
        await registration("Светлана", "Михайлова", "Учитель", "test11@gmail.com", "1234")  
        await registration("Павел", "Захаров", "Учитель", "test12@gmail.com", "1234")       
        await registration("Ирина", "Лебедева", "Учитель", "test13@gmail.com", "1234")      

        await createClass("7-A", 1)  
        await createClass("8-А", 11) 
        await createClass("8-Б", 5)  
        await createClass("11-A", 9) 
        await createClass("11-Б", 7) 

        await createStudent("Максим", "Егоров", 1)           
        await createStudent("Анастасия", "Федорова", 1)      
        await createStudent("Илья", "Костин", 1)             
        await createStudent("Дарья", "Григорьева", 1)        
        await createStudent("Роман", "Сухов", 1)             

        await createStudent("Екатерина", "Алексеева", 2)        
        await createStudent("Владислав", "Мартынов", 2)         
        await createStudent("Юлия", "Тихонова", 2)              

        await createStudent("Артем", "Лисицын", 3)              
        await createStudent("Полина", "Соловьева", 3)           
        await createStudent("Никита", "Панкратов", 3)           

        await createStudent("Никита", "Котелев", 4)             
        await createStudent("Павел", "Далецкий", 4)             
        await createStudent("Александр", "Гисак", 4)            
        await createStudent("Роман", "Королёв", 4)              

        await createStudent("Денис", "Осмоловский", 5)          
        await createStudent("Кирилл", "Козлов", 5)              
        await createStudent("Константин", "Альхимович", 5)      
        await createStudent("Матвей", "Шаблинский", 5)          
        await createStudent("Тимофей", "Марков", 5)             

        
        await createAttendance(1, true, "2024-12-26")      
        await createAttendance(2, false, "2024-12-26")     
        await createAttendance(3, false, "2024-12-26")     
        await createAttendance(4, true, "2024-12-26")      
        await createAttendance(5, true, "2024-12-26")      
        await createAttendance(6, false, "2024-12-26")     
        await createAttendance(7, false, "2024-12-26")     
        await createAttendance(8, false, "2024-12-26")     
        await createAttendance(9, true, "2024-12-26")      
        await createAttendance(10, false, "2024-12-26")     
        await createAttendance(11, true, "2024-12-26")      
        await createAttendance(12, false, "2024-12-26")     
        await createAttendance(13, true, "2024-12-26")      
        await createAttendance(14, true, "2024-12-26")      
        await createAttendance(15, false, "2024-12-26")     
        await createAttendance(16, false, "2024-12-26")     
        await createAttendance(17, true, "2024-12-26")      
        await createAttendance(18, false, "2024-12-26")     
        await createAttendance(19, true, "2024-12-26")      
        await createAttendance(20, false, "2024-12-26")     

        await createAttendance(1, false, "2024-12-27")      
        await createAttendance(2, true, "2024-12-27")       
        await createAttendance(3, true, "2024-12-27")       
        await createAttendance(4, false, "2024-12-27")      
        await createAttendance(5, true, "2024-12-27")       
        await createAttendance(6, false, "2024-12-27")      
        await createAttendance(7, false, "2024-12-27")      
        await createAttendance(8, true, "2024-12-27")       
        await createAttendance(9, true, "2024-12-27")       
        await createAttendance(10, true, "2024-12-27")      
        await createAttendance(11, false, "2024-12-27")     
        await createAttendance(12, true, "2024-12-27")      
        await createAttendance(13, false, "2024-12-27")     
        await createAttendance(14, true, "2024-12-27")      
        await createAttendance(15, true, "2024-12-27")      
        await createAttendance(16, true, "2024-12-27")      
        await createAttendance(17, false, "2024-12-27")     
        await createAttendance(18, false, "2024-12-27")     
        await createAttendance(19, false, "2024-12-27")     
        await createAttendance(20, true, "2024-12-27")      
        const formData1 = new FormData()
        formData1.append('name', "Математика")
        formData1.append('date', "2024-12-1")
        formData1.append('type', "Олимпиада")
        formData1.append('file', null)
        await createEvent(formData1)
        const formData2 = new FormData()
        formData2.append('name', "11-Б")
        formData2.append('date', "2024-12-2")
        formData2.append('type', "Родительское собрание")
        formData2.append('file', null)
        await createEvent(formData2)
        const formData3 = new FormData()
        formData3.append('name', "7-А")
        formData3.append('date', "2024-12-3")
        formData3.append('type', "Классный час")
        formData3.append('file', null)
        await createEvent(formData3)
        const formData4 = new FormData()
        formData4.append('name', "Несвижский замок")
        formData4.append('date', "2024-12-4")
        formData4.append('type', "Экскурсия")
        formData4.append('file', null)
        await createEvent(formData4)
        const formData5 = new FormData()
        formData5.append('name', "Лучший танцор")
        formData5.append('date', "2024-12-5")
        formData5.append('type', "Конкурс")
        formData5.append('file', null)
        await createEvent(formData5)
        const formData6 = new FormData()
        formData6.append('name', "Вред курения")
        formData6.append('date', "2024-12-6")
        formData6.append('type', "Поучающее видео")
        formData6.append('file', null)
        await createEvent(formData6)

        await createParticipant(2, null, 1, 1)
        await createParticipant(11, null, 1, 2)
        await createParticipant(6, null, 1, 3)

        await createParticipant(null, 5, 2, null)

        await createParticipant(null, 1, 3, null)

        await createParticipant(null, 2, 4, null)
        await createParticipant(null, 3, 4, null)

        await createParticipant(4, null, 5, 1)
        await createParticipant(10, null, 5, 2)
        await createParticipant(13, null, 5, 3)

        await createParticipant(null, 5, 6, null)
        await createParticipant(null, 3, 6, null)
}