// nutritionspdf.js
export default ({ employee, nutritions, participants, students, classes }) => {
    console.log("Template received data:", { employee, nutritions, participants, students, classes });

    return `
        <!doctype html>
        <html>
            <head>
                <meta charset="utf-8">
                <title>Nutrition Report</title>
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
                <style>
                    .report-box {
                        max-width: 800px;
                        margin: auto;
                        padding: 30px;
                        border: 1px solid #ddd;
                        box-shadow: 0 0 10px rgba(0, 0, 0, .1);
                        font-size: 16px;
                        line-height: 24px;
                        font-family: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
                        color: #333;
                    }
                    .justify-center {
                        text-align: center;
                    }
                    .report-box table {
                        width: 100%;
                        line-height: inherit;
                        text-align: left;
                    }
                    .report-box table td {
                        padding: 10px;
                        vertical-align: top;
                    }
                    .report-box table tr.heading td {
                        background: #f8f9fa;
                        font-weight: bold;
                    }
                    .report-box table tr.item td {
                        border-bottom: 1px solid #dee2e6;
                    }
                </style>
            </head>
            <body>
                <div class="report-box">
                    <h2 class="justify-center">Nutrition Report</h2>
                    <p class="justify-center">Generated by: ${employee?.name || 'System'}</p>
                    <p>Nutrition Details:</p>
                    <table class="table">
                        <thead>
                            <tr class="heading">
                                <th>Date</th>
                                <th>Name</th>
                                <th>Type</th>
                                <th>Participants</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${Array.isArray(nutritions) ? nutritions.map(nutrition => `
                                <tr class="item">
                                    <td>${new Date(nutrition.date).toLocaleDateString()}</td>
                                    <td>${nutrition.name || 'N/A'}</td>
                                    <td>${nutrition.type || 'N/A'}</td>
                                    <td>${Array.isArray(participants) ? participants.filter(p => p.nutritionNutritionId === nutrition.nutrition_id).length : 0}</td>
                                </tr>
                            `).join('') : 'No nutrition data available'}
                        </tbody>
                    </table>
                </div>
            </body>
        </html>
    `;
};